CREATE DATABASE something_db;

CREATE TABLE user(
	id INTEGER(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
	username VARCHAR(30) NOT NULL,
    pword VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    phone INTEGER(11) NOT NULL
);